anguage: node_js
node_js:
 -  "7"

dist: trusty
sudo: false
group: edge

addons:
  sonarqube:
    organization: "chowanioksource"
    branches :
      - master
      - develop
    token:
      secure: iMtbkxdiFeoiV5n8YJfs9Lg5kInhIVF1QkfpcxGj/BiLUZKg/Dx0bQ6NSrm+u937aEAV4K2xX+PVHgiUyVL16da7ImI+LUgF8F+8RecSrpjK8g1lSdu9E2FoZ+ySzfZ2IgrjWHdHDiFr0keV3uyrGvqhrSZwn/vV0B7YKlc83AET7WEAOR582P2Z5OGL+uyJgso2egGvVdfwmxOjBNcUxi1HvZSdsRZb4XsT1lphV/WKDhPkNBRD9jnvzB45qvJyBR+slir2cTPur5IhSyuQd+wSeSG+USro7bG9N84V5RKnnr24JbywBF/Qgf9cV8CPwnoSXuYWrVojsESBMZ6TwDxtqa9vbEgviXeCgrUEOKmm1VHDtPWC3ynmMuqyqPMGgUmDavbMPYoAtJp/MvDQNyfcseaFabhmQU2b1Jyo1nNMTYNO2fTD7GzwsEot+Ys6K5tK+HFSE+JxItsABer45AYM/sfqxiXoIRVf/5dbK1xLNgX9T0cz1eMNTBSohYlubcV5kwwI8UdHHZ0hltuNRB5P7cwBYwI+jkvYkHJv2Nlf/iwS3BIUS1PcCZALRZtN6IV7JBjjgxDYGxP1ge5+li7YoByOgz8Xp1oq0O1Jp7Dmvt5Wa8pbvMY6WFingjc9I5/wHs65ey2PS7D/cXZpu9CcPTRh/lkCjAXqt+QaDSY=

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
    - node_modules
